# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push:
    tags:
      - '*/*.*/*.*.*' # chrome/119.0/0.0.1

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set env
        run: |
          echo "RELEASE_VERSION=$(cut -d '/' -f 3 <<< "${GITHUB_REF#refs/*/}")" >> $GITHUB_ENV
          echo "BROWSER_VERSION=$(cut -d '/' -f 2 <<< "${GITHUB_REF#refs/*/}")" >> $GITHUB_ENV
          echo "BROWSER=$(cut -d '/' -f 1 <<< "${GITHUB_REF#refs/*/}")" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: dumptec/selenoid_webdriver

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Dockerfiles/${{ env.BROWSER }}/${{ env.BROWSER_VERSION }}/
          push: true
          tags: |
            dumptec/selenoid_webdriver:${{ env.BROWSER }}_${{ env.BROWSER_VERSION }}-${{ env.RELEASE_VERSION }}
            dumptec/selenoid_webdriver:${{ env.BROWSER }}_${{ env.BROWSER_VERSION }}-latest
          labels: ${{ steps.meta.outputs.labels }}
